prayerlabs_profile:
    pattern:  /
    defaults: { _controller: "PrayerlabsMyprofileBundle:Profile:index" }
prayerlabs_profile_signup:
    pattern:  /signup
    defaults: { _controller: "PrayerlabsMyprofileBundle:Profile:signUp" }
prayerlabs_profile_edit:
    pattern:  /editProfile
    defaults: { _controller: "PrayerlabsMyprofileBundle:Profile:editProfile" }
prayerlabs_profile_logout:
    pattern:  /logout
    defaults: { _controller: "PrayerlabsMyprofileBundle:Profile:logout" }
prayerlabs_profile_change_password:
    pattern:  /changePassword
    defaults: { _controller: "PrayerlabsMyprofileBundle:Profile:changePassword" }
prayerlabs_profile_email_verification:
    pattern:  /profileVerify
    defaults: { _controller: "PrayerlabsMyprofileBundle:Profile:profileVerify" }
prayerlabs_profile_thanks:
    pattern:  /thanks
    defaults: { _controller: "PrayerlabsMyprofileBundle:Profile:thanks" }
    