Prayerlabs\MyprofileBundle\Entity\Prayed:
  type: entity
  table: prayed
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  manyToOne:
    accounts:
      targetEntity: Accounts
      inversedBy: prayed
      joinColumn:
        name: account_id
        referencedColumnName: id
    posts:
      targetEntity: Posts
      inversedBy: prayed
      joinColumn:
        name: post_id
        referencedColumnName: id