parameters:
#    prayerlabs_myprofile.example.class: Prayerlabs\MyprofileBundle\Example

services:
#    prayerlabs_myprofile.example:
#        class: %prayerlabs_myprofile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
